language: cpp
sudo: false
dist: trusty

#install:
# - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install llvm; fi


matrix:
  include:
    - os: linux
      compiler: clang
      env: MAKEFLAG="-j2"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
            - llvm-toolchain-trusty
            - sourceline: 'ppa:mhier/libboost-latest'
          packages:
            - g++-multilib
            - gcc-multilib
            - gcc-7-multilib
            - g++-7-multilib
            - bzip2
            - clang-5.0
            - libc6-dbg
            - boost1.67
script:
  - sudo find / -name "libz.a" -print
  - sudo find / -name "libz.so" -print
  - sudo find / -name "zconf.h" -print
  - sudo find / -name "libboost*" -print
  - sudo find / -name "openssl*" -print
  - echo $MAKEFLAG
