language: cpp
sudo: false

install:
 - if [ "$TRAVIS_OS_NAME" == "osx"]; then brew install llvm; fi

matrix:
  include:
    - os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise
            - llvm-toolchain-precise-3.9
          packages:
            - clang-3.9
            - lib32z1-dev
    - os: osx
      compiler: clang
script:
  - sudo find / -name "zlib*"
