language: cpp
sudo: false
dist: bionic

if: type != push OR branch = master OR branch =~ /^v\d+\.\d+(\.\d+)?(-\S*)?$/

#install:
# - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install llvm; fi


matrix:
  include:
    - os: osx
      compiler: clang
    - os: linux
      compiler: clang
      env: MAKEFLAG="-j2" TEST_FLAG="-DABC=1"
      addons:
        apt:
          sources:
#            - ubuntu-toolchain-r-test
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
#            - llvm-toolchain-bionic-8
#            - llvm-toolchain-bionic
            - sourceline: 'ppa:mhier/libboost-latest'
          packages:
#            - g++-multilib
#            - gcc-multilib
#            - gcc-7-multilib
#            - g++-7-multilib
#            - bzip2
            - clang-8
            - g++-9
#            - gcov-9
#            - libc6-dbg
            - boost1.67
script:
#  - sudo find / -name "libz.a" -print
#  - sudo find / -name "libz.so" -print
#  - sudo find / -name "zconf.h" -print
#  - sudo find / -name "libboost*" -print
#  - sudo find / -name "openssl*" -print
  - ls -l /usr/local/opt/openssl/
  - ls -l /usr/local/opt/openssl/include
  - tree /usr/local/opt/openssl/
  - TEST_FLAG="${TEST_FLAG} -DDEF=2"
  - echo $TEST_FLAG
  - echo $MAKEFLAG
  - g++ --version
  - gcov --version
  - clang++ --version
  - g++-9 --version
  - clang++-8 --version
