language: cpp
os:
  - osx
  - linux

env:
  - ACTION="echo" PARAM="cpp11"
  - ACTION="echo" PARAM="cpp03"

matrix:
  exclude:
    - os: osx
      env: ACTION="echo" PARAM="cpp03"
    - os: linux
      env: ACTION="echo" PARAM="cpp11"
script:
  - git clean -xdf && ${ACTION} ${PARAM}
