language: cpp
sudo: false
dist: precise

install:
 - if [ "$TRAVIS_OS_NAME" == "osx"]; then brew install llvm; fi

matrix:
  include:
    - os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise
            - llvm-toolchain-precise-3.9
            - lib32z1-dev
          packages:
            - clang-3.9
    - os: osx
      compiler: clang
script:
  - clang --version && find / -name "zconf.h"
