language: cpp
os:
  - osx
  - linux

before_install:
  - echo "before install osx1"
  - echo "before install osx2"
  - echo "before install linux1"
  - echo "before install linux2"
env:
  - ACTION="echo" PARAM="A"
  - ACTION="echo" PARAM="B"
  - ACTION="echo" PARAM="C"

matrix:
  exclude:
    - os: osx
      env: ACTION="echo" PARAM="A"
      before_install: echo "before install linux1"
    - os: osx
      env: ACTION="echo" PARAM="B"
      before_install: echo "before install linux2"
    - os: linux
      env: ACTION="echo" PARAM="C"
      before_install: echo "before install osx1"
script:
  - git clean -xdf && ${ACTION} ${PARAM}
