language: cpp
sudo: false
dist: precise

matrix:
  include:
    - os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - llvm-toolchain-precise-4.0
          packages:
            - clang-4.0
script:
  - clang --version
