language: cpp
sudo: false
dist: precise

matrix:
  include:
    - os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-precise
          packages:
            - clang-4.0
script:
  - clang --version
