language: cpp
os:
  - osx
  - linux

compiler:
  - clang
  - gcc

before_install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then echo "before install osx1"; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then echo "before install osx2"; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then echo "before install linux1"; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then echo "before install linux2"; fi
  - pwd

env:
  - ACTION="echo" PARAM="A"
  - ACTION="echo" PARAM="B"
  - ACTION="echo" PARAM="C"

matrix:
  exclude:
    - os: osx
      compiler: gcc
    - os: osx
      env: ACTION="echo" PARAM="B"
    - os: osx
      env: ACTION="echo" PARAM="C"
    - os: linux
      env: ACTION="echo" PARAM="A"
    - os: linux
      env: ACTION="echo" PARAM="C"
script:
  - git clean -xdf && ${ACTION} ${PARAM} && pwd
