language: cpp
os:
  - osx

compiler:
  - clang

before_install:
install:
branches:
env:
  - ACTION="echo" PARAM="cpp11"
  - ACTION="echo" PARAM="cpp03"

matrix:

script:
  - git clean -xdf && ${ACTION} ${PARAM}
