language: cpp
sudo: false
dist: trusty

#install:
# - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install llvm; fi

matrix:
  include:
    - os: linux
      compiler: clang
      env: MAKEFLAG="-j2"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise
            - llvm-toolchain-precise-3.9
          packages:
#            - clang-3.9
#            - lib64z1-dev
             - lib32z1-dev
             - zlib1g-dev
#    - os: osx
#      compiler: clang
script:
  - sudo find / -name "libz.a" -print
  - sudo find / -name "libz.so" -print
  - sudo find / -name "zconf.h" -print
  - echo $MAKEFLAG
